version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:22181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  spark-master:
    image: docker.io/sdesilva26/spark_master:latest
    container_name: spark
    ports:
      - '8080:8080'
    networks:
      - spark-net
    deploy:
      placement:
        constraints:
          - node.labels.role==master
  spark-worker:
    image: docker.io/sdesilva26/spark_worker:latest
    container_name: spark-worker
    ports:
      - '8081:8081'
    environment:
      - CORES=1
      - MEMORY=1G
    deploy:
      placement:
        constraints:
          - node.labels.role==worker
    networks:
      - spark-net
  spark-submit:
    image: docker.io/sdesilva26/spark_submit:latest
    container_name: spark-submit
    ports:
      - '4040:4040'
    networks:
      - spark-net
    tty: true
      
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - 7070:7070
    environment:
      TRINO_ENVIRONMENT: production
      TRINO_NODE_ENVIRONMENT: production
      TRINO_DISCOVERY_URI: http://trino:8080
      TRINO_DISCOVERY_SERVER_ENABLED: 'true'
      
networks:
  spark-net:
    name: spark-net
